[project]
name = 'Secure-Digital-Identity-for-Financial-Inclusion'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.credential-issuance]
path = 'contracts/credential-issuance.clar'
clarity_version = 2
epoch = 2.5

[contracts.identity-creation]
path = 'contracts/identity-creation.clar'
clarity_version = 2
epoch = 2.5

[contracts.service-access]
path = 'contracts/service-access.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
